server:
  port: 1234
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/restful-api
    username: kotlin
    password: kotlin123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
